[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; img-src 'self'; script-src 'unsafe-inline' https://www.googletagmanager.com 'self'; style-src-elem 'self' https://fonts.googleapis.com;"
    Content-Security-Policy = "default-src 'self';"
    Content-Security-Policy = "connect-src 'https://google.com'"
