[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https://*:*; script-src 'unsafe-inline' https://*:*;"
    Cf-Ray = "test-value-12345"
    Cf-Mitigated = "some-cf-mitigated-value?"
